// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mppkdtetvnkdyzcveeoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcGtkdGV0dm5rZHl6Y3ZlZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4ODExOTgsImV4cCI6MjA1NDQ1NzE5OH0.efGw3H2GNjy8yCI-kfC8RnQZZ83d_f487djeNk5jFrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);